# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buss_choices', models.IntegerField(choices=[(1, 'O2M300'), (2, 'O2M500'), (3, 'O2M800'), (4, 'IM300'), (5, 'IM500'), (6, 'IM800')])),
            ],
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virIP', models.GenericIPAddressField(db_index=True, verbose_name='虚拟IP')),
                ('physicalIP', models.GenericIPAddressField(null=True, verbose_name='对应物理IP')),
                ('application', models.CharField(db_index=True, max_length=200, verbose_name='应用名称')),
                ('port', models.CharField(max_length=100, verbose_name='应用端口')),
                ('component', models.CharField(max_length=100, verbose_name='组件用途')),
                ('principal', models.CharField(max_length=32, verbose_name='开发负责人')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('note', models.CharField(max_length=100, null=True, verbose_name='备注')),
                ('Bussiness_idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Bussiness', verbose_name='关联业务线')),
            ],
        ),
        migrations.CreateModel(
            name='Lalancing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lalancing_choices', models.IntegerField(choices=[(1, '无'), (2, '有')])),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_choices', models.IntegerField(choices=[(1, '测试'), (2, '生产')])),
            ],
        ),
        migrations.AddField(
            model_name='idc',
            name='Lalancing_idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Lalancing', verbose_name='负载均衡'),
        ),
        migrations.AddField(
            model_name='idc',
            name='Produce_idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Produce', verbose_name='生产测试'),
        ),
    ]
