# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='port',
            field=models.IntegerField(max_length=100, verbose_name='应用端口'),
        ),
    ]
