# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180608_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussiness',
            name='buss_choices',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='Lalancing_idc',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='Produce_idc',
        ),
        migrations.AddField(
            model_name='bussiness',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='idc',
            name='lalancing_choices',
            field=models.IntegerField(choices=[(1, '无'), (2, '有')], null=True),
        ),
        migrations.DeleteModel(
            name='Lalancing',
        ),
        migrations.DeleteModel(
            name='Produce',
        ),
    ]
