# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180611_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='port',
            field=models.IntegerField(max_length=100, null=True, verbose_name='应用端口'),
        ),
    ]
