# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'permissions': (('view_userinfo', '访问用户列表'),)},
        ),
    ]
